# Generated by Django 4.1.7 on 2023-05-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='orderproduct',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='patronimic',
            new_name='patronymic',
        ),
    ]
